vm restore updated

diff --git a/k8s-rpi-apps-victoriametrics-h-k/overlays/add/vmrestore-script-configmap.yaml b/k8s-rpi-apps-victoriametrics-h-k/overlays/add/vmrestore-script-configmap.yaml
--- a/k8s-rpi-apps-victoriametrics-h-k/overlays/add/vmrestore-script-configmap.yaml
+++ b/k8s-rpi-apps-victoriametrics-h-k/overlays/add/vmrestore-script-configmap.yaml
@@ -8,6 +8,4 @@ metadata:
 data:
   restore.sh: |
     #!/bin/sh
-    set -e
-    /vmrestore-prod -storageDataPath=/storage -src=s3://<bucket>/backups/vm -credsFilePath=/etc/vmbackup-config/config.ini -customS3Endpoint=<s3endpoint>
-    echo "Restore successful"
+    /vmrestore-prod -storageDataPath=/storage -src=s3://<bucket>/backups/vm -credsFilePath=/etc/vmbackup-config/config.ini -customS3Endpoint=<s3endpoint> && echo "Restore successful" || echo "Restore failed"
